In [1]:
import numpy as np
from szegedy import SzegedyRandomWalk

I'm tracking the number of steps it takes for the probability in starting point to reach > 0.75.

In [90]:
def test_resetting_rate(n, resetting_func):
    times = np.zeros(n)
    
    for i in range(2, n):
        # crete the matrix
        matrix = np.zeros((i, i))
        # add loop for starting point
        matrix[0][0] = 1
        
        # add resetting edges and loops
        for j in range(1, i):
            matrix[j][0] = resetting_func(i)
            matrix[j][j] = 1 - matrix[j][0]
        
        # print(matrix)
            
        szegedy = SzegedyRandomWalk(matrix)
            
        # starting position
        if i == 1:
            initial_state = np.array([0, 1])
        else:
            initial_state = np.ones(i)
            initial_state[0] = 0
        initial_state_H = np.kron(initial_state, initial_state) * 1 / np.sqrt(i - 1)
        
        # print(f"Initial state: {initial_state_H}")
        
        # perform walk
        t = 1
        state = initial_state_H
        while t < 100:
            # print(szegedy.state_at(t, initial_state_H))
            # print(np.power(szegedy.state_at(t, initial_state_H), 2).reshape((i,i)).sum(axis=1))
            # print("---")
            state = szegedy.operator @ state
            if np.power(state, 2).reshape((i,i)).sum(axis=1)[0] > 0.5:
                times[i] = t
                break
            t += 1
        if t == 100:
            times[i] = "inf"
    
    return times

In [71]:
test_resetting_rate(50, lambda x: 1)

array([ 0.,  0.,  3.,  4.,  6.,  8.,  9., 11., 12., 14., 16., 17., 19.,
       20., 22., 24., 25., 27., 28., 30., 32., 33., 35., 37., 38., 40.,
       41., 43., 45., 46., 48., 50., 51., 53., 54., 56., 58., 59., 61.,
       63., 64., 66., 67., 69., 71., 72., 74., 76., 77., 79.])

In [73]:
test_resetting_rate(50, lambda x: 4 / x)

array([ 0.,  0., inf,  2.,  3.,  4.,  4.,  5.,  6.,  7.,  8.,  8.,  9.,
       10., 11., 12., 12., 13., 14., 15., 16., 16., 17., 18., 19., 20.,
       20., 21., 22., 23., 24., 24., 25., 26., 27., 28., 28., 29., 30.,
       31., 32., 32., 33., 34., 35., 36., 37., 37., 38., 39.])

In [74]:
test_resetting_rate(50, lambda x: 4 / np.sqrt(x))

array([ 0.,  0., inf,  4.,  2.,  2.,  3.,  3.,  4.,  4.,  4.,  4.,  5.,
        5.,  5.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  9.,
        9.,  9.,  9., 10., 10., 10., 10., 11., 11., 11., 11., 12., 12.,
       12., 12., 13., 13., 13., 13., 13., 14., 14., 14., 14.])

In [92]:
test_resetting_rate(50, lambda x: 1 / 5)

array([0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])