In [1]:
import numpy as np
from szegedy import SzegedyRandomWalk

In [12]:
def perform_walk(matrix, steps):
    # create operator
    szegedy = SzegedyRandomWalk(matrix)
    
    # get initial state
    initial_state = szegedy.classic_initial_state()
    
    # perform evolution
    states = szegedy.state_history(steps, initial_state)
    
    # show measurements
    measurements = szegedy.original_state_history(steps, initial_state)
    
    return initial_state, np.round(states, decimals=2), np.round(measurements, decimals=2)

### Graph of size 4

#### With resetting

In [2]:
walk_with_resetting = np.asarray([[0.5, 0.25, 0, 0.25], [0.5, 0, 0.25, 0.25], [0.5, 0, 0, 0.5], [0.5, 0, 0.5, 0]])
walk_with_resetting

array([[0.5 , 0.25, 0.  , 0.25],
       [0.5 , 0.  , 0.25, 0.25],
       [0.5 , 0.  , 0.  , 0.5 ],
       [0.5 , 0.  , 0.5 , 0.  ]])

In [13]:
initial_state1, states1, measurements1 = perform_walk(walk_with_resetting, 10)

In [14]:
initial_state1

array([0.35355339, 0.25      , 0.        , 0.25      , 0.35355339,
       0.        , 0.25      , 0.25      , 0.35355339, 0.        ,
       0.        , 0.35355339, 0.35355339, 0.        , 0.35355339,
       0.        ])

In [15]:
states1

array([[ 0.35,  0.25,  0.  ,  0.25,  0.35,  0.  ,  0.25,  0.25,  0.35,
         0.  ,  0.  ,  0.35,  0.35,  0.  ,  0.35,  0.  ],
       [ 0.25,  0.53, -0.35,  0.18, -0.35,  0.  ,  0.18,  0.18,  0.25,
        -0.18,  0.  , -0.35,  0.  , -0.18,  0.25,  0.  ],
       [-0.43, -0.23, -0.25, -0.12, -0.25,  0.  ,  0.25,  0.25,  0.18,
        -0.38,  0.  , -0.25, -0.35, -0.38,  0.  ,  0.  ],
       [-0.55, -0.16,  0.  , -0.44, -0.35,  0.  , -0.25, -0.25, -0.12,
         0.16,  0.  , -0.18, -0.25,  0.16, -0.25,  0.  ],
       [ 0.04, -0.5 ,  0.25, -0.1 ,  0.35,  0.  , -0.24, -0.24, -0.44,
         0.11,  0.  ,  0.12, -0.  ,  0.11, -0.44,  0.  ],
       [ 0.2 ,  0.16,  0.44,  0.2 ,  0.34,  0.  , -0.11, -0.11, -0.1 ,
         0.36,  0.  ,  0.44,  0.25,  0.36,  0.2 ,  0.  ],
       [ 0.67,  0.26, -0.2 ,  0.33,  0.15,  0.  ,  0.07,  0.07,  0.2 ,
        -0.11,  0.  ,  0.1 ,  0.44, -0.11,  0.19,  0.  ],
       [-0.04,  0.43, -0.19,  0.17, -0.1 ,  0.  ,  0.44,  0.44,  0.33,
        -0.19,  0.  , -0.2

In [16]:
measurements1

array([[0.25, 0.25, 0.25, 0.25],
       [0.5 , 0.19, 0.22, 0.09],
       [0.31, 0.19, 0.23, 0.27],
       [0.53, 0.25, 0.07, 0.15],
       [0.33, 0.24, 0.22, 0.21],
       [0.3 , 0.14, 0.33, 0.23],
       [0.66, 0.03, 0.06, 0.24],
       [0.25, 0.39, 0.18, 0.18],
       [0.26, 0.39, 0.22, 0.13],
       [0.61, 0.01, 0.07, 0.31]])

#### Without resetting

In [7]:
walk_without_resetting = np.asarray([[0, 0.5, 0, 0.5], [0, 0, 0.5, 0.5], [0.5, 0, 0, 0.5], [0.5, 0, 0.5, 0]])

In [17]:
initial_state2, states2, measurements2 = perform_walk(walk_without_resetting, 10)

In [18]:
initial_state2

array([0.        , 0.35355339, 0.        , 0.35355339, 0.        ,
       0.        , 0.35355339, 0.35355339, 0.35355339, 0.        ,
       0.        , 0.35355339, 0.35355339, 0.        , 0.35355339,
       0.        ])

In [19]:
states2

array([[ 0.  ,  0.35,  0.  ,  0.35,  0.  ,  0.  ,  0.35,  0.35,  0.35,
         0.  ,  0.  ,  0.35,  0.35,  0.  ,  0.35,  0.  ],
       [ 0.  ,  0.35, -0.35, -0.35, -0.35,  0.  , -0.35, -0.35,  0.35,
         0.  ,  0.  , -0.35,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.35, -0.  , -0.35, -0.  ,  0.  ,  0.35,  0.35, -0.35,
         0.  ,  0.  , -0.35, -0.35,  0.  , -0.35,  0.  ],
       [ 0.  , -0.35,  0.35,  0.35,  0.35,  0.  , -0.35, -0.35, -0.35,
         0.  ,  0.  ,  0.35, -0.  ,  0.  , -0.  ,  0.  ],
       [ 0.  ,  0.35,  0.  ,  0.35,  0.  ,  0.  ,  0.35,  0.35,  0.35,
         0.  ,  0.  ,  0.35,  0.35,  0.  ,  0.35,  0.  ],
       [ 0.  ,  0.35, -0.35, -0.35, -0.35,  0.  , -0.35, -0.35,  0.35,
         0.  ,  0.  , -0.35,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.35, -0.  , -0.35, -0.  ,  0.  ,  0.35,  0.35, -0.35,
         0.  ,  0.  , -0.35, -0.35,  0.  , -0.35,  0.  ],
       [ 0.  , -0.35,  0.35,  0.35,  0.35,  0.  , -0.35, -0.35, -0.35,
         0.  ,  0.  ,  0.3

In [20]:
measurements2

array([[0.25, 0.25, 0.25, 0.25],
       [0.38, 0.38, 0.25, 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.38, 0.38, 0.25, 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.38, 0.38, 0.25, 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.38, 0.38, 0.25, 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.38, 0.38, 0.25, 0.  ]])

### Graph of size 8 + marked

In [22]:
walk_with_resetting_bigger = np.asarray([[0.5, 0.25, 0, 0.25, 0, 0, 0, 0],
                                         [0.5, 0, 0.25, 0, 0.25, 0, 0, 0],
                                         [0.5, 0, 0.5, 0, 0, 0, 0, 0],
                                         [0.5, 0, 0, 0, 0.5, 0, 0, 0],
                                         [0.5, 0, 0, 0, 0, 0.5, 0, 0],
                                         [0.5, 0, 0, 0, 0, 0, 0.25, 0.25],
                                         [0.5, 0, 0, 0.5, 0, 0, 0, 0],
                                         [0.5, 0, 0, 0, 0, 0, 0.5, 0],])

In [23]:
initial_state3, states3, measurements3 = perform_walk(walk_with_resetting_bigger, 10)

In [24]:
initial_state3

array([0.25     , 0.1767767, 0.       , 0.1767767, 0.       , 0.       ,
       0.       , 0.       , 0.25     , 0.       , 0.1767767, 0.       ,
       0.1767767, 0.       , 0.       , 0.       , 0.25     , 0.       ,
       0.25     , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.25     , 0.       , 0.       , 0.       , 0.25     , 0.       ,
       0.       , 0.       , 0.25     , 0.       , 0.       , 0.       ,
       0.       , 0.25     , 0.       , 0.       , 0.25     , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.1767767, 0.1767767,
       0.25     , 0.       , 0.       , 0.25     , 0.       , 0.       ,
       0.       , 0.       , 0.25     , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.25     , 0.       ])

In [25]:
states3

array([[ 0.25,  0.18,  0.  ,  0.18,  0.  ,  0.  ,  0.  ,  0.  ,  0.25,
         0.  ,  0.18,  0.  ,  0.18,  0.  ,  0.  ,  0.  ,  0.25,  0.  ,
         0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.25,  0.  ,  0.  ,
         0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,
         0.  ,  0.25,  0.  ,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.18,  0.18,  0.25,  0.  ,  0.  ,  0.25,  0.  ,  0.  ,
         0.  ,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.25,
         0.  ],
       [ 0.  ,  0.25, -0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.  , -0.25,
         0.  ,  0.13,  0.  ,  0.12,  0.  ,  0.  ,  0.  ,  0.  , -0.12,
        -0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.25,  0.  ,  0.  ,
         0.  ,  0.18,  0.  ,  0.  ,  0.  , -0.25, -0.12,  0.  , -0.18,
         0.  , -0.25,  0.  ,  0.  , -0.25,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.18, -0.18, -0.25,  0.  ,  0.  , -0.25,  0.  ,  0.  ,
         0.  ,  0.  , -0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0. 

In [26]:
measurements3

array([[0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.12],
       [0.19, 0.09, 0.08, 0.09, 0.17, 0.13, 0.13, 0.13],
       [0.25, 0.03, 0.09, 0.03, 0.22, 0.13, 0.13, 0.13],
       [0.19, 0.03, 0.16, 0.03, 0.22, 0.13, 0.13, 0.13],
       [0.19, 0.09, 0.08, 0.09, 0.17, 0.13, 0.13, 0.13],
       [0.19, 0.13, 0.06, 0.13, 0.13, 0.13, 0.13, 0.13],
       [0.13, 0.09, 0.14, 0.09, 0.17, 0.13, 0.13, 0.13],
       [0.25, 0.03, 0.09, 0.03, 0.22, 0.13, 0.13, 0.13],
       [0.25, 0.03, 0.09, 0.03, 0.22, 0.13, 0.13, 0.13],
       [0.13, 0.09, 0.14, 0.09, 0.17, 0.13, 0.13, 0.13]])

#### Without resetting

In [27]:
walk_without_resetting_bigger = np.asarray([[0, 0.5, 0, 0.5, 0, 0, 0, 0],
                                            [0, 0, 0.5, 0, 0.5, 0, 0, 0],
                                            [0, 0, 1, 0, 0, 0, 0, 0],
                                            [0, 0, 0, 0, 1, 0, 0, 0],
                                            [0, 0, 0, 0, 0, 1, 0, 0],
                                            [0, 0, 0, 0, 0, 0, 0.5, 0.5],
                                            [0, 0, 0, 1, 0, 0, 0, 0],
                                            [0, 0, 0, 0, 0, 0, 1, 0],])

In [28]:
initial_state4, states4, measurements4 = perform_walk(walk_without_resetting_bigger, 10)

In [29]:
initial_state4

array([0.        , 0.25      , 0.        , 0.25      , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25      , 0.        , 0.25      , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.35355339, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.35355339, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.35355339, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.25      , 0.25      , 0.        , 0.        ,
       0.        , 0.35355339, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.35355339, 0.        ])

In [30]:
states4

array([[ 0.  ,  0.25,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.25,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.35,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.35,
         0.  ],
       [ 0.  , -0.25,  0.  , -0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.25,  0.  , -0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.25, -0.25,  0.  ,  0.  ,  0.  , -0.35,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0. 

In [31]:
measurements4

array([[0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12],
       [0.13, 0.13, 0.12, 0.12, 0.12, 0.13, 0.12, 0.12]])

### Complete graph of size 6

In [32]:
complete_graph = np.full((6, 6), 0.2)
complete_graph -= np.diag([0.2] * 6)
complete_graph

array([[0. , 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0. , 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0. , 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0. , 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0. , 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0. ]])

In [33]:
initial_state5, states5, measurements5 = perform_walk(complete_graph, 10)

In [34]:
initial_state5

array([0.        , 0.18257419, 0.18257419, 0.18257419, 0.18257419,
       0.18257419, 0.18257419, 0.        , 0.18257419, 0.18257419,
       0.18257419, 0.18257419, 0.18257419, 0.18257419, 0.        ,
       0.18257419, 0.18257419, 0.18257419, 0.18257419, 0.18257419,
       0.18257419, 0.        , 0.18257419, 0.18257419, 0.18257419,
       0.18257419, 0.18257419, 0.18257419, 0.        , 0.18257419,
       0.18257419, 0.18257419, 0.18257419, 0.18257419, 0.18257419,
       0.        ])

In [35]:
states5

array([[0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18,
        0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  ,
        0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18,
        0.18, 0.18, 0.  ],
       [0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18,
        0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  ,
        0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18,
        0.18, 0.18, 0.  ],
       [0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18,
        0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  ,
        0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18,
        0.18, 0.18, 0.  ],
       [0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18,
        0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  ,
        0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.  , 0.18, 0.18, 0.18, 0.18,
        0.18, 0.18, 0.  ],
    

In [36]:
measurements5

array([[0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17]])